### ISSUE TITLE
Add task list for citation tool

### ISSUE THREAD

**Issue by cherriechang** [jspsych/jspsych-contrib#132]

**Comment by cchang-vassar** [comment]
End goal: dev can build an experiment, open inspect and type a standardized jsPsych command that generates a citation list (bibliography?) of plugins and extensions used.
- [ ] Research: what style of citation, what kind of file/object generated
- [ ] Develop: in contrib citation info would be a file in the package? or a line in package.json? Depends on above

What about for timelines? e.g. an experiment that imports multiple different timelines other devs developed?
- [ ] Develop: in timelines
